# Running this Docker image requires Docker to support NVIDIA GPUs. Please make sure NVIDIA Container Toolkit is configured.
# See https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/index.html https://github.com/NVIDIA/nvidia-docker

FROM nvidia/cuda:11.4.3-devel-ubuntu20.04

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt install -y cmake vim wget git zip unzip

RUN mkdir /opt/packages && \
    cd /opt/packages && \
    wget https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz && \
    tar -xzvf boost_1_77_0.tar.gz && \
    rm boost_1_77_0.tar.gz && \
    cd boost_1_77_0/ && \
    ./bootstrap.sh && \
    ./b2 && \
    ./b2 install && \
    cd /opt && rm -rf /opt/packages

COPY . /opt/unidock

RUN cd /opt/unidock && \
    cmake -B build && \
    cmake --build build -j`nprocs` && \
    cmake --install build && \
    rm -r /opt/unidock
