from typing import List, Tuple, Dict, Union, Optional
from pathlib import Path
import logging
import os
import shutil
import subprocess
import math

from unidock_tools.utils import randstr, make_tmp_dir, time_logger


class UniDockRunner:
    def __init__(self,
                 receptor: Union[str, Path, os.PathLike],
                 ligands: List[Path],
                 center_x: float,
                 center_y: float,
                 center_z: float,
                 size_x: float = 22.5,
                 size_y: float = 22.5,
                 size_z: float = 22.5,
                 output_dir: Optional[Union[str, os.PathLike]] = None,
                 scoring: str = "vina",
                 num_modes: int = 10,
                 search_mode: str = "",
                 exhaustiveness: int = 256,
                 max_step: int = 10,
                 energy_range: float = 3.0,
                 refine_step: int = 5,
                 seed : int = 181129,
                 score_only: bool = False,
                 local_only: bool = False
                 ):
        self.mgltools_python_path = ""
        self.prepare_gpf4_script_path = ""
        self.ad4_map_data_path = ""
        self.check_env(scoring == "ad4")

        self.workdir = make_tmp_dir("unidock")
        cmd = ["unidock"]

        if score_only:
            size_x = min(size_x*2, 25)
            size_y = min(size_y*2, 25)
            size_z = min(size_z*2, 25)

        if scoring.lower() == "ad4":
            map_prefix = os.path.join(self.workdir, 'receptor_grids','protein_conf_0', 'protein.maps.fld')
            cmd += ["--maps", str(map_prefix)]
        else:
            cmd += ["--receptor", str(receptor)]

        ligand_index_path = os.path.join(self.workdir, f"ligand_index_{randstr()}.txt")
        with open(ligand_index_path, "w") as f:
            f.write("\n".join([str(ligand) for ligand in ligands]))
        cmd += ["--ligand_index", ligand_index_path]

        if not output_dir:
            output_dir = os.path.join(self.workdir, "results_dir")
        cmd += ["--dir", str(output_dir)]

        if search_mode:
            cmd += ["--search_mode", search_mode]
        else:
            cmd += [
                "--exhaustiveness", str(exhaustiveness),
                "--max_step", str(max_step),
            ]

        cmd += [
            "--center_x", str(center_x),
            "--center_y", str(center_y),
            "--center_z", str(center_z),
            "--size_x", str(size_x),
            "--size_y", str(size_y),
            "--size_z", str(size_z),
            "--scoring", scoring,
            "--num_modes", str(num_modes),
            "--energy_range", str(energy_range),
            "--refine_step", str(refine_step),
            "--seed", str(seed),
            "--verbosity", "2",
            "--keep_nonpolar_H",
        ]
        if score_only:
            cmd.append("--score_only")
        if local_only:
            cmd.append("--local_only")

        logging.info(f"unidock cmd: {' '.join(cmd)}")
        self.cmd = cmd

        self.pre_result_ligands = [Path(os.path.join(output_dir, f"{l.stem}_out.sdf")) for l in ligands]


    def run(self):
        resp = subprocess.run(
            self.cmd,
            capture_output=True,
            encoding="utf-8",
        )
        logging.debug(f"Run Uni-Dock log: {resp.stdout}")
        if resp.returncode != 0:
            logging.info(f"Run Uni-Dock log\n{resp.stdout}")
            logging.error(f"Run Uni-Dock error\n{resp.stderr}")

        result_ligands = [f for f in self.pre_result_ligands if os.path.exists(f)]
        return result_ligands

    @staticmethod
    def read_scores(ligand_file: Union[str, bytes, os.PathLike]) -> List[float]:
        score_list = []
        with open(ligand_file, "r") as f:
            lines = f.readlines()
            for idx, line in enumerate(lines):
                if line.startswith("> <Uni-Dock RESULT>"):
                    score = float(lines[idx + 1].partition(
                        "LOWER_BOUND=")[0][len("ENERGY="):])
                    score_list.append(score)
        return score_list

    @staticmethod
    def read_score_txt(txt_file: Union[str, bytes, os.PathLike]) -> Dict[str, float]:
        """Read scores.txt file which is generated by Uni-Dock score_only mode and get score value.

        Args:
            txt_file (Union[str, bytes, os.PathLike]): scores.txt file

        Returns:
            List[Tuple[str, float]]: List of (file_base, score) tuples
        """
        file_score_dict = dict()
        with open(txt_file, "r") as f:
            for line in f.readlines():
                if line.startswith("REMARK"):
                    line_list = line.strip().split(" ")
                    file_base = line_list[1]
                    score = float(line_list[2])
                    file_score_dict[file_base] = score
        return file_score_dict

    def clean_workdir(self):
        shutil.rmtree(self.workdir, ignore_errors=True)


@time_logger
def run_unidock(
        receptor: Path,
        ligands: List[Path],
        output_dir: Path,
        center_x: float,
        center_y: float,
        center_z: float,
        size_x: float = 22.5,
        size_y: float = 22.5,
        size_z: float = 22.5,
        scoring: str = "vina",
        num_modes: int = 10,
        search_mode: str = "",
        exhaustiveness: int = 256,
        max_step: int = 10,
        energy_range: float = 3.0,
        refine_step: int = 5,
        seed: int = 181129,
        score_only: bool = False,
        local_only: bool = False,
) -> Tuple[List[Path], List[List[float]]]:
    runner = UniDockRunner(
        receptor=receptor, ligands=ligands,
        center_x=center_x, center_y=center_y, center_z=center_z,
        size_x=size_x, size_y=size_y, size_z=size_z,
        output_dir=output_dir,
        scoring=scoring, num_modes=num_modes,
        search_mode=search_mode,
        exhaustiveness=exhaustiveness, max_step=max_step,
        energy_range=energy_range, refine_step=refine_step, seed=seed,
        score_only=score_only, local_only=local_only,
    )
    result_ligands = runner.run()
    scores_list = [UniDockRunner.read_scores(ligand) for ligand in result_ligands]
    if score_only:
        scores_txt = os.path.join(output_dir, "scores.txt")
        filename_score_dict = UniDockRunner.read_score_txt(scores_txt)
        result_ligands = ligands
        scores_list = [[filename_score_dict[os.path.basename(fpath)]] for fpath in result_ligands]
    runner.clean_workdir()

    return result_ligands, scores_list
