ARG CUDA_VERSION=12.0.0
FROM nvidia/cuda:${CUDA_VERSION}-devel-ubuntu22.04

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get clean && apt-get update \
    && apt-get install -y build-essential zip unzip vim git wget

RUN wget -O conda.sh \
    https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh \
    && bash conda.sh -b -p /opt/conda \
    && rm conda.sh
ENV PATH /opt/conda/bin:$PATH

RUN wget -O CDPKit.sh https://github.com/molinfo-vienna/CDPKit/releases/download/v1.1.0/CDPKit-1.1.0-Linux-x86_64.sh  && \
    echo y | bash CDPKit.sh --cpack_skip_license --include-subdir && \
    rm CDPKit.sh

WORKDIR /opt
RUN mamba install -y ipython rdkit openbabel networkx numpy pandas -c conda-forge
RUN mamba create -y -n mgltools mgltools autogrid -c bioconda
ENV PATH $PATH:/opt/conda/envs/mgltools/bin
RUN pip install tqdm
