RESIDUE_PARAMETER_DICT = {
  "ALA": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB1",   "HB2",   "HB3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "H"],
  },
  "CYS": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "SG",    "HG"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",    "SA",    "HD"],
  },
  "CYX": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "SG"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",    "SA"],
  },
  "CYM": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "SG"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",    "SA"],
  },
  "CME": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB3",   "HB2",    "SG",     "SD",    "CE",    "HE2",   "HE3",   "CZ",   "HZ3",   "HZ2",  "OH",   "HH"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",    "SA",     "SA",     "C",     "H",     "H",     "C",    "H",     "H",   "OA",   "HD"],
  },
  "ASP": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "OD1",   "OD2"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",    "OA",    "OA"],
  },
  "ASH": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "OD1",   "OD2",   "HD2"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",    "OA",    "OA",    "HD"],
  },
  "GLU": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "HG2",   "HG3",    "CD",   "OE1",   "OE2"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",     "H",     "H",     "C",    "OA",    "OA"],
  },
  "GLH": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "HG2",   "HG3",    "CD",   "OE1",   "OE2",   "HE2"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",     "H",     "H",     "C",    "OA",    "OA",    "HD"],
  },
  "PHE": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "CD1",   "HD1",   "CE1",   "HE1",    "CZ",    "HZ",   "CE2",   "HE2",   "CD2",   "HD2"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "A",     "A",     "H",     "A",     "H",     "A",     "H",     "A",     "H",     "A",     "H"],
  },
  "GLY": {
        "atom_names": [     "C",     "O",    "CA",   "HA2",     "N",     "H",   "HA3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "H"],
  },
  "HIE": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "ND1",   "CE1",   "HE1",   "NE2",   "HE2",   "CD2",   "HD2"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "A",    "NA",     "A",     "H",     "N",    "HD",     "A",     "H"],
  },
  "HID": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "ND1",   "HD1",   "CE1",   "HE1",   "NE2",   "CD2",   "HD2"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "A",     "N",    "HD",     "A",     "H",    "NA",     "A",     "H"],
  },
  "HIP": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "ND1",   "HD1",   "CE1",   "HE1",   "NE2",   "HE2",   "CD2",   "HD2"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "A",     "N",    "HD",     "A",     "H",     "N",    "HD",     "A",     "H"],
  },
  "ILE": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",    "HB",   "CG2",  "HG21",  "HG22",  "HG23",   "CG1",  "HG12",  "HG13",   "CD1",  "HD11",  "HD12",  "HD13"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "C",     "H",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",     "H"],
  },
  "LYS": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB3",   "HB2",    "CG",   "HG2",   "HG3",    "CD",   "HD2",   "HD3",    "CE",   "HE2",   "HE3",    "NZ",   "HZ1",   "HZ2",   "HZ3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",     "N",    "HD",    "HD",    "HD"],
  },
  "LYN": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB3",   "HB2",    "CG",   "HG2",   "HG3",    "CD",   "HD2",   "HD3",    "CE",   "HE2",   "HE3",    "NZ",   "HZ2",   "HZ3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",    "NA",    "HD",    "HD"],
  },
  "LEU": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",    "HG",   "CD1",  "HD11",  "HD12",  "HD13",   "CD2",  "HD21",  "HD22",  "HD23"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",     "H",     "C",     "H",     "H",     "H",     "C",     "H",     "H",     "H"],
  },
  "MET": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB3",   "HB2",    "CG",   "HG2",   "HG3",    "SD",    "CE",   "HE1",   "HE2",   "HE3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",     "H",     "H",    "SA",     "C",     "H",     "H",     "H"],
  },
  "ASN": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "OD1",   "ND2",  "HD22",  "HD21"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",    "OA",     "N",    "HD",    "HD"],
  },
  "PRO": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB3",   "HB2",    "CG",   "HG2",   "HG3",    "CD",   "HD2",   "HD3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H"],
  },
  "GLN": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "HG2",   "HG3",    "CD",   "OE1",   "NE2",  "HE22",  "HE21"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",     "H",     "H",     "C",    "OA",     "N",    "HD",    "HD"],
  },
  "ARG": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB3",   "HB2",    "CG",   "HG2",   "HG3",    "CD",   "HD2",   "HD3",    "NE",    "HE",    "CZ",   "NH1",  "HH12",  "HH11",   "NH2",  "HH22",  "HH21"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",     "N",    "HD",     "C",     "N",    "HD",    "HD",     "N",    "HD",    "HD"],
  },
  "SER": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "OG",    "HG"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",    "OA",    "HD"],
  },
  "THR": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",    "HB",   "CG2",  "HG21",  "HG22",  "HG23",   "OG1",   "HG1"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "C",     "H",     "H",     "H",    "OA",    "HD"],
  },
  "VAL": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",    "HB",   "CG1",  "HG11",  "HG12",  "HG13",   "CG2",  "HG21",  "HG22",  "HG23"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "C",     "H",     "H",     "H",     "C",     "H",     "H",     "H"],
  },
  "TRP": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "CD1",   "HD1",   "NE1",   "HE1",   "CE2",   "CD2",   "CE3",   "HE3",   "CZ3",   "HZ3",   "CH2",   "HH2",   "CZ2",   "HZ2"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "A",     "A",     "H",     "N",    "HD",     "A",     "A",     "A",     "H",     "A",     "H",     "A",     "H",     "A",     "H"],
  },
  "TYR": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "CD1",   "HD1",   "CE1",   "HE1",    "CZ",    "OH",    "HH",   "CE2",   "HE2",   "CD2",   "HD2"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "A",     "A",     "H",     "A",     "H",     "A",    "OA",    "HD",     "A",     "H",     "A",     "H"],
  },
  "NME": {
        "atom_names": [   "CH3",  "HH31",  "HH32",  "HH33",     "N",     "H"],
        "atom_types": [     "C",     "H",     "H",     "H",     "N",    "HD"],
  },
  "ACE": {
        "atom_names": [     "C",     "O",   "CH3",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "H",     "H"],
  },
  "NPRO": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "H2",    "H3",    "CB",   "HB3",   "HB2",    "CG",   "HG2",   "HG3",    "CD",   "HD2",   "HD3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",    "HD",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H"],
  },
  "NALA": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB1",   "HB2",   "HB3",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "H",    "HD",    "HD",    "HD"],
  },
  "NCYS": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "SG",    "HG",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",    "SA",    "HD",    "HD",    "HD",    "HD"],
  },
  "NCYX": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "SG",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",    "SA",    "HD",    "HD",    "HD"],
  },
  "NCYM": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "SG",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",    "SA",    "HD",    "HD",    "HD"],
  },
  "NASP": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "CG",   "OD1",   "OD2",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "C",    "OA",    "OA",    "HD",    "HD",    "HD"],
  },
  "NASH": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "CG",   "OD1",   "OD2",   "HD2",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "C",    "OA",    "OA",    "HD",    "HD",    "HD",    "HD"],
  },
  "NGLU": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "CG",   "HG2",   "HG3",    "CD",   "OE1",   "OE2",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "C",     "H",     "H",     "C",    "OA",    "OA",    "HD",    "HD",    "HD"],
  },
  "NGLH": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "CG",   "HG2",   "HG3",    "CD",   "OE1",   "OE2",   "HE2",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "C",     "H",     "H",     "C",    "OA",    "OA",    "HD",    "HD",    "HD",    "HD"],
  },
  "NPHE": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "CG",   "CD1",   "HD1",   "CE1",   "HE1",    "CZ",    "HZ",   "CE2",   "HE2",   "CD2",   "HD2",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "A",     "A",     "H",     "A",     "H",     "A",     "H",     "A",     "H",     "A",     "H",    "HD",    "HD",    "HD"],
  },
  "NGLY": {
        "atom_names": [     "C",     "O",    "CA",   "HA2",     "N",   "HA3",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "H",    "HD",    "HD",    "HD"],
  },
  "NHIE": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "CG",   "ND1",   "CE1",   "HE1",   "NE2",   "HE2",   "CD2",   "HD2",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "A",    "NA",     "A",     "H",     "N",    "HD",     "A",     "H",    "HD",    "HD",    "HD"],
  },
  "NHID": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "CG",   "ND1",   "HD1",   "CE1",   "HE1",   "NE2",   "CD2",   "HD2",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "A",     "N",    "HD",     "A",     "H",    "NA",     "A",     "H",    "HD",    "HD",    "HD"],
  },
  "NHIP": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "CG",   "ND1",   "HD1",   "CE1",   "HE1",   "NE2",   "HE2",   "CD2",   "HD2",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "A",     "N",    "HD",     "A",     "H",     "N",    "HD",     "A",     "H",    "HD",    "HD",    "HD"],
  },
  "NILE": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",    "HB",   "CG2",  "HG21",  "HG22",  "HG23",   "CG1",  "HG12",  "HG13",   "CD1",  "HD11",  "HD12",  "HD13",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "C",     "H",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",     "H",    "HD",    "HD",    "HD"],
  },
  "NLYS": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB3",   "HB2",    "CG",   "HG2",   "HG3",    "CD",   "HD2",   "HD3",    "CE",   "HE2",   "HE3",    "NZ",   "HZ1",   "HZ2",   "HZ3",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",     "N",    "HD",    "HD",    "HD",    "HD",    "HD",    "HD"],
  },
  "NLYN": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB3",   "HB2",    "CG",   "HG2",   "HG3",    "CD",   "HD2",   "HD3",    "CE",   "HE2",   "HE3",    "NZ",   "HZ2",   "HZ3",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",    "NA",    "HD",    "HD",    "HD",    "HD",    "HD"],
  },
  "NLEU": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "CG",    "HG",   "CD1",  "HD11",  "HD12",  "HD13",   "CD2",  "HD21",  "HD22",  "HD23",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "C",     "H",     "C",     "H",     "H",     "H",     "C",     "H",     "H",     "H",    "HD",    "HD",    "HD"],
  },
  "NMET": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB3",   "HB2",    "CG",   "HG2",   "HG3",    "SD",    "CE",   "HE1",   "HE2",   "HE3",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "C",     "H",     "H",    "SA",     "C",     "H",     "H",     "H",    "HD",    "HD",    "HD"],
  },
  "NASN": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "CG",   "OD1",   "ND2",  "HD22",  "HD21",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "C",    "OA",     "N",    "HD",    "HD",    "HD",    "HD",    "HD"],
  },
  "NGLN": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "CG",   "HG2",   "HG3",    "CD",   "OE1",   "NE2",  "HE22",  "HE21",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "C",     "H",     "H",     "C",    "OA",     "N",    "HD",    "HD",    "HD",    "HD",    "HD"],
  },
  "NARG": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB3",   "HB2",    "CG",   "HG2",   "HG3",    "CD",   "HD2",   "HD3",    "NE",    "HE",    "CZ",   "NH1",  "HH12",  "HH11",   "NH2",  "HH22",  "HH21",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",     "N",    "HD",     "C",     "N",    "HD",    "HD",     "N",    "HD",    "HD",    "HD",    "HD",    "HD"],
  },
  "NSER": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "OG",    "HG",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",    "OA",    "HD",    "HD",    "HD",    "HD"],
  },
  "NTHR": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",    "HB",   "CG2",  "HG21",  "HG22",  "HG23",   "OG1",   "HG1",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "C",     "H",     "H",     "H",    "OA",    "HD",    "HD",    "HD",    "HD"],
  },
  "NVAL": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",    "HB",   "CG1",  "HG11",  "HG12",  "HG13",   "CG2",  "HG21",  "HG22",  "HG23",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "C",     "H",     "H",     "H",     "C",     "H",     "H",     "H",    "HD",    "HD",    "HD"],
  },
  "NTRP": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "CG",   "CD1",   "HD1",   "NE1",   "HE1",   "CE2",   "CD2",   "CE3",   "HE3",   "CZ3",   "HZ3",   "CH2",   "HH2",   "CZ2",   "HZ2",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "A",     "A",     "H",     "N",    "HD",     "A",     "A",     "A",     "H",     "A",     "H",     "A",     "H",     "A",     "H",    "HD",    "HD",    "HD"],
  },
  "NTYR": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB2",   "HB3",    "CG",   "CD1",   "HD1",   "CE1",   "HE1",    "CZ",    "OH",    "HH",   "CE2",   "HE2",   "CD2",   "HD2",    "H1",    "H2",    "H3"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "A",     "A",     "H",     "A",     "H",     "A",    "OA",    "HD",     "A",     "H",     "A",     "H",    "HD",    "HD",    "HD"],
  },
  "CALA": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB1",   "HB2",   "HB3",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "H",    "OA"],
  },
  "CCYS": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "SG",    "HG",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",    "SA",    "HD",    "OA"],
  },
  "CCYX": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "SG",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",    "SA",    "OA"],
  },
  "CCYM": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "SG",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",    "SA",    "OA"],
  },
  "CASP": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "OD1",   "OD2",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",    "OA",    "OA",    "OA"],
  },
  "CASH": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "OD1",   "OD2",   "HD2",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",    "OA",    "OA",    "HD",    "OA"],
  },
  "CGLU": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "HG2",   "HG3",    "CD",   "OE1",   "OE2",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",     "H",     "H",     "C",    "OA",    "OA",    "OA"],
  },
  "CGLH": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "HG2",   "HG3",    "CD",   "OE1",   "OE2",   "HE2",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",     "H",     "H",     "C",    "OA",    "OA",    "HD",    "OA"],
  },
  "CPHE": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "CD1",   "HD1",   "CE1",   "HE1",    "CZ",    "HZ",   "CE2",   "HE2",   "CD2",   "HD2",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "A",     "A",     "H",     "A",     "H",     "A",     "H",     "A",     "H",     "A",     "H",    "OA"],
  },
  "CGLY": {
        "atom_names": [     "C",     "O",    "CA",   "HA2",     "N",     "H",   "HA3",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "H",    "OA"],
  },
  "CHIE": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "ND1",   "CE1",   "HE1",   "NE2",   "HE2",   "CD2",   "HD2",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "A",    "NA",     "A",     "H",     "N",    "HD",     "A",     "H",    "OA"],
  },
  "CHID": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "ND1",   "HD1",   "CE1",   "HE1",   "NE2",   "CD2",   "HD2",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "A",     "N",    "HD",     "A",     "H",    "NA",     "A",     "H",    "OA"],
  },
  "CHIP": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "ND1",   "HD1",   "CE1",   "HE1",   "NE2",   "HE2",   "CD2",   "HD2",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "A",     "N",    "HD",     "A",     "H",     "N",    "HD",     "A",     "H",    "OA"],
  },
  "CILE": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",    "HB",   "CG2",  "HG21",  "HG22",  "HG23",   "CG1",  "HG12",  "HG13",   "CD1",  "HD11",  "HD12",  "HD13",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "C",     "H",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",     "H",    "OA"],
  },
  "CLYS": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB3",   "HB2",    "CG",   "HG2",   "HG3",    "CD",   "HD2",   "HD3",    "CE",   "HE2",   "HE3",    "NZ",   "HZ1",   "HZ2",   "HZ3",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",     "N",    "HD",    "HD",    "HD",    "OA"],
  },
  "CLYN": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB3",   "HB2",    "CG",   "HG2",   "HG3",    "CD",   "HD2",   "HD3",    "CE",   "HE2",   "HE3",    "NZ",   "HZ2",   "HZ3",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",    "NA",    "HD",    "HD",    "OA"],
  },
  "CLEU": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",    "HG",   "CD1",  "HD11",  "HD12",  "HD13",   "CD2",  "HD21",  "HD22",  "HD23",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",     "H",     "C",     "H",     "H",     "H",     "C",     "H",     "H",     "H",    "OA"],
  },
  "CMET": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB3",   "HB2",    "CG",   "HG2",   "HG3",    "SD",    "CE",   "HE1",   "HE2",   "HE3",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",     "H",     "H",    "SA",     "C",     "H",     "H",     "H",    "OA"],
  },
  "CASN": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "OD1",   "ND2",  "HD22",  "HD21",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",    "OA",     "N",    "HD",    "HD",    "OA"],
  },
  "CGLN": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "HG2",   "HG3",    "CD",   "OE1",   "NE2",  "HE22",  "HE21",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",     "H",     "H",     "C",    "OA",     "N",    "HD",    "HD",    "OA"],
  },
  "CARG": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB3",   "HB2",    "CG",   "HG2",   "HG3",    "CD",   "HD2",   "HD3",    "NE",    "HE",    "CZ",   "NH1",  "HH12",  "HH11",   "NH2",  "HH22",  "HH21",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",     "N",    "HD",     "C",     "N",    "HD",    "HD",     "N",    "HD",    "HD",    "OA"],
  },
  "CSER": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "OG",    "HG",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",    "OA",    "HD",    "OA"],
  },
  "CTHR": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",    "HB",   "CG2",  "HG21",  "HG22",  "HG23",   "OG1",   "HG1",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "C",     "H",     "H",     "H",    "OA",    "HD",    "OA"],
  },
  "CVAL": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",    "HB",   "CG1",  "HG11",  "HG12",  "HG13",   "CG2",  "HG21",  "HG22",  "HG23",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "C",     "H",     "H",     "H",     "C",     "H",     "H",     "H",    "OA"],
  },
  "CTRP": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "CD1",   "HD1",   "NE1",   "HE1",   "CE2",   "CD2",   "CE3",   "HE3",   "CZ3",   "HZ3",   "CH2",   "HH2",   "CZ2",   "HZ2",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "A",     "A",     "H",     "N",    "HD",     "A",     "A",     "A",     "H",     "A",     "H",     "A",     "H",     "A",     "H",    "OA"],
  },
  "CTYR": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",     "H",    "CB",   "HB2",   "HB3",    "CG",   "CD1",   "HD1",   "CE1",   "HE1",    "CZ",    "OH",    "HH",   "CE2",   "HE2",   "CD2",   "HD2",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",    "HD",     "C",     "H",     "H",     "A",     "A",     "H",     "A",     "H",     "A",    "OA",    "HD",     "A",     "H",     "A",     "H",    "OA"],
  },
  "CPRO": {
        "atom_names": [     "C",     "O",    "CA",    "HA",     "N",    "CB",   "HB3",   "HB2",    "CG",   "HG2",   "HG3",    "CD",   "HD2",   "HD3",   "OXT"],
        "atom_types": [     "C",    "OA",     "C",     "H",     "N",     "C",     "H",     "H",     "C",     "H",     "H",     "C",     "H",     "H",    "OA"],
  },
  "AIB": {
        "atom_names": ["N", "CA", "C", "O", "CB1", "CB2",  "H", "HB11", "HB12", "HB13", "HB21", "HB22", "HB23"], 
        "atom_types": ["N",  "C", "C", "OA", "C",   "C",   "HD",   "H",    "H",    "H",    "H",    "H",    "H"],
  },
  "0AO": {"atom_names": ["N", "CA", "C", "O", "C3", "C4", "C5", "C13", "C6", "C8", "C7", "C12", "C9", "C10", "C11",  "H", "HA", "H11", "H12", "H1", "H2", "H13", "H7", "H3", "H5", "H6"], 
          "atom_types": ["N", "C", "C", "OA", "C",   "A",  "A",  "A",   "A",  "A",  "A",  "A",   "A",  "A",    "A",  "HD", "H",  "H",   "H",   "H",  "H",  "H",   "H",  "H",  "H",  "H"],
  },
  "200": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "CD2", "CD1", "CE2", "CE1", "CZ", "CL",  "H", "HA", "HB2", "HB3", "HD2", "HD1", "HE2", "HE1"], 
          "atom_types": ["N", "C", "C", "OA", "C",  "A",   "A",   "A",   "A",   "A",   "A", "Cl", "HD", "H",   "H",   "H",   "H",   "H",   "H",   "H"],
  },
  "ABA": {"atom_names": ["N", "CA", "C", "O", "CB", "CG",  "H", "HA", "HB2", "HB3", "HG2", "HG3", "HG1"], 
          "atom_types": ["N",  "C", "C", "OA", "C", "C",   "HD", "H",   "H",   "H",   "H",   "H",   "H"],
  },
  "ASQ": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "OD1", "OD2", "P", "O1P", "O2P", "O3P",   "H", "HA", "HB2", "HB3"], 
          "atom_types": ["N", "C",  "C", "OA", "C", "C",   "OA",  "OA", "P",  "OA",  "OA",  "OA",   "HD", "H",  "H",    "H"],
  },
  "BCS": {"atom_names": ["N", "CA", "C", "O", "CB", "SG", "CD", "CE", "CZ1", "CT1", "CH", "CT2", "CZ2",   "H", "HA", "HB2", "HB3", "HD2", "HD3", "HZ1", "HT1", "HH", "HT2", "HZ2"], 
          "atom_types": ["N", "C",  "C", "OA", "C", "SA",  "C",  "A",   "A",   "A",  "A",   "A",   "A",   "HD", "H",   "H",   "H",   "H",   "H",   "H",   "H",  "H",  "H",   "H"],
  },
  "DAL": {"atom_names": ["N", "CA", "C", "O", "CB",   "H", "HA", "HB1", "HB2", "HB3"], 
          "atom_types": ["N", "C",  "C", "OA", "C",   "HD",  "H",  "H",  "H",  "H"],
  },
  "DAR": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "CD", "NE", "CZ", "NH1", "NH2",  "H", "HA", "HB2", "HB3", "HG2", "HG3", "HD2", "HD3", "HE", "HH12", "HH11", "HH22", "HH21"], 
          "atom_types": ["N", "C", "C", "OA",  "C",  "C",  "C",  "N",  "C",  "N",    "N",  "HD", "H",  "H",   "H",   "H",   "H",   "H",   "H",  "HD",   "HD",   "HD",   "HD",   "HD"],
  },
  "DAS": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "OD1", "OD2",  "H", "HA", "HB2", "HB3"], 
          "atom_types": ["N", "C",  "C", "OA", "C", "C",   "OA",  "OA",  "HD", "H",   "H",   "H"],
  },
  "DCY": {"atom_names": ["N", "CA", "C", "O", "CB", "SG",  "H", "HA", "HB2", "HB3", "HG"], 
          "atom_types": ["N", "C", "C", "OA",  "C", "SA",   "HD", "H",  "H",  "H",  "HD"],
  },
  "DGL": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "CD", "OE1", "OE2",  "H", "HA", "HB2", "HB3", "HG2", "HG3"], 
          "atom_types": ["N", "C", "C", "OA",  "C", "C",   "C", "OA",  "OA",   "HD", "H",   "H",  "H",   "H",   "H"],
  }, 
  "DGN": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "CD", "OE1", "NE2",  "H", "HA", "HB2", "HB3", "HG2", "HG3", "HE22", "HE21"], 
          "atom_types": ["N", "C",  "C", "OA", "C", "C",   "C", "OA",   "N",    "HD", "H",   "H",  "H",    "H",  "H",    "HD",   "HD"],
  },
  "DHI": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "ND1", "CD2", "CE1", "NE2",  "H", "HA", "HB2", "HB3", "HD1", "HD2", "HE1"], 
          "atom_types": ["N", "C",  "C", "OA", "C",  "A",   "N",   "A",   "A",  "NA",   "HD", "H",  "H",   "H",  "HD",   "H",   "H"],
  }, 
  "DIL": {"atom_names": ["N", "CA", "C", "O", "CB", "CG1", "CG2", "CD1",  "H", "HA", "HB", "HG12", "HG13", "HG21", "HG22", "HG23", "HD11", "HD12", "HD13"], 
          "atom_types": ["N", "C",  "C", "OA", "C",  "C",   "C",   "C",    "HD", "H", "H",    "H",    "H",    "H",    "H",    "H",    "H",    "H",    "H"],
  }, 
  "DLE": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "CD1", "CD2",  "H", "HA", "HB2", "HB3", "HG", "HD11", "HD12", "HD13", "HD21", "HD22", "HD23"], 
          "atom_types": ["N",  "C", "C", "OA", "C",  "C",  "C",   "C",   "HD", "H",   "H",   "H",  "H",   "H",    "H",    "H",    "H",    "H",    "H"],
  },
  "DLY": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "CD", "CE", "NZ",  "H", "HA", "HB2", "HB3", "HG2", "HG3", "HD2", "HD3", "HE2", "HE3", "HZ1", "HZ2", "HZ3"], 
          "atom_types": ["N", "C", "C", "OA", "C", "C", "C", "C", "N", "OA",  "H", "H", "H", "H", "H", "H", "H", "H", "H", "HD", "HD", "HD"],
  }, 
  "DPN": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "CD1", "CD2", "CE1", "CE2", "CZ",   "H", "HA", "HB2", "HB3", "HD1", "HD2", "HE1", "HE2", "HZ"], 
          "atom_types": ["N", "C",  "C", "OA", "C",  "A",   "A",   "A",   "A",   "A",  "A",  "HD", "H", "H", "H", "H", "H", "H", "H", "H"],
  },
  "DPR": {"atom_names": ["CD", "N", "CA", "C", "O", "CB", "CG",   "HD2", "HD3", "HA", "HB3", "HB2", "HG2", "HG3"], 
          "atom_types": ["C",  "N", "C",  "C", "OA", "C",  "C",   "H", "H", "H", "H", "H", "H", "H"],
  }, 
  "DSG": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "OD1", "ND2",   "H", "HA", "HB2", "HB3", "HD22", "HD21"], 
          "atom_types": ["N", "C",  "C", "OA", "C",  "C",  "OA",  "N",    "HD", "H",   "H",   "H",   "HD", "HD"],
  },
  "DSN": {"atom_names": ["N", "CA", "C", "O", "CB", "OG",   "H", "HA", "HB2", "HB3", "HG"], 
          "atom_types": ["N", "C", "C", "OA", "C", "OA",   "HD", "H", "H", "H", "HD"],
  },
  "DTH": {"atom_names": ["N", "CA", "C", "O", "CB", "OG1", "CG2",   "H", "HA", "HB", "HG1", "HG21", "HG22", "HG23"], 
          "atom_types": ["N", "C",  "C", "OA", "C",  "OA",   "C",   "HD", "H", "H", "HD", "H", "H", "H"],
  },
  "DTR": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "CD1", "CD2", "NE1", "CE2", "CE3", "CZ2", "CZ3", "CH2",   "H", "HA", "HB2", "HB3", "HD1", "HE1", "HE3", "HZ2", "HZ3", "HH2"], 
          "atom_types": ["N", "C", "C", "OA", "C",   "A",   "A",   "A",   "N",   "A",   "A",   "A",   "A",   "A",    "HD", "H", "H", "H", "H", "HD", "H", "H", "H", "H"],
  },
  "DTY": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "CD1", "CD2", "CE1", "CE2", "CZ", "OH",   "H", "HA", "HB2", "HB3", "HD1", "HD2", "HE1", "HE2", "HH"], 
          "atom_types": ["N", "C",  "C", "OA", "C", "A",   "A",   "A",    "A",  "A",   "A",  "OA", "HD", "H", "H", "H", "H", "H", "H", "H", "HD"],
  }, 
  "DVA": {"atom_names": ["N", "CA", "C", "O", "CB", "CG1", "CG2",   "H", "HA", "HB", "HG11", "HG12", "HG13", "HG21", "HG22", "HG23"], 
          "atom_types": ["N", "C",  "C", "OA", "C",   "C",  "C",    "HD", "H", "H", "H", "H", "H", "H", "H", "H"],
  }, 
  "EBZ": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "CD", "OE1", "OE2", "C1", "C2", "C3", "C4", "C5", "C6", "C7",   "H", "HA", "HB2", "HB3", "HG2", "HG3", "HC11", "HC12", "HC3", "HC4", "HC5", "HC6", "HC7"], 
          "atom_types": ["N", "C", "C", "OA",  "C",  "C",  "C", "OA",   "OA",  "C",  "A",  "A",  "A",  "A",  "A",  "A",   "HD", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],
  }, 
  "GNC": {"atom_names": ["C1", "N", "CA", "C", "O", "CB", "CG", "CD", "OE", "NE",   "HC3", "HC1", "HC2", "HA", "HB2", "HB3", "HG3", "HG2", "HE21", "HE22"], 
          "atom_types": ["C",  "N", "C",  "C", "OA", "C",  "C",  "C", "OA",  "N",    "H", "H", "H", "H", "H", "H", "H", "H", "HD", "HD"],
  }, 
  "HBZ": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "ND1", "CD2", "CE1", "NE2", "C1", "C2", "C3", "C4", "C5", "C6", "C7",   "H", "HA", "HB2", "HB3", "HD2", "HE1", "HC11", "HC12", "HC3", "HC4", "HC5", "HC6", "HC7"], 
          "atom_types": ["N", "C",  "C", "OA", "C",  "A",  "NA",   "A",   "A",   "N",  "C",  "A",  "A",  "A",  "A",  "A",  "A",   "HD", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],
  },
  "HYP": {"atom_names": ["CD", "N", "CA", "C", "O", "CB", "CG", "OD",   "HD3", "HD2", "HA", "HB2", "HB3", "HG", "HD"], 
          "atom_types": ["C",  "N",  "C", "C", "OA", "C", "C",  "OA",    "H", "H", "H", "H", "H", "H", "HD"],
  }, 
  "MEA": {"atom_names": ["C1", "N", "CA", "C", "O", "CB", "CG", "CD1", "CD2", "CE1", "CE2", "CZ",   "HC1", "HC2", "HC3", "HA", "HB1", "HB2", "HD1", "HD2", "HE1", "HE2", "HZ"], 
          "atom_types": ["A", "N",   "A", "A", "OA", "C", "A",   "A",   "A",   "A",   "A",   "A",   "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],
  },
  "MED": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "SD", "CE",   "H", "HA", "HB2", "HB3", "HG2", "HG3", "HE1", "HE2", "HE3"], 
          "atom_types": ["N", "C",  "C", "OA", "C", "C",  "SA",  "C",   "HD", "H", "H", "H", "H", "H", "H", "H", "H"],
  },
  "MSE": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "SE", "CE",   "H", "HA", "HB2", "HB3", "HG2", "HG3", "HE1", "HE2", "HE3"], 
          "atom_types": ["N", "C",  "C", "OA", "C", "C",  "Se",  "C",   "HD", "H", "H", "H", "H", "H", "H", "H", "H"],
  }, 
  "NA8": {"atom_names": ["N", "CA", "C", "O", "C9", "C2", "C3", "C1", "C4", "C8A", "C4A", "C8", "C5", "C6", "C7",   "H", "HA", "H92C", "H91C", "H3", "H1", "H4", "H8", "H5", "H6", "H7"], 
          "atom_types": ["N", "C", "C", "OA",  "C",  "A",  "A",  "A",  "A",   "A",   "A",  "A",  "A",  "A",  "A",   "HD", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],
  }, 
  "NLE": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "CD", "CE",   "H", "HA", "HB2", "HB3", "HG2", "HG3", "HD2", "HD3", "HE2", "HE3", "HE1"], 
          "atom_types": ["N", "C", "C", "OA",  "C",  "C", "C",  "C",    "HD", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],
  }, 
  "NVA": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "CD",   "H", "HA", "HB3", "HB2", "HG3", "HG2", "HD1", "HD2", "HD3"], 
          "atom_types": ["N", "C", "C", "OA",  "C",  "C",  "C",   "HD", "H", "H", "H", "H", "H", "H", "H", "H"],
  },
  "PTR": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "CD1", "CD2", "CE1", "CE2", "CZ", "OH", "P", "O1P", "O2P", "O3P",   "H", "HA", "HB2", "HB3", "HD1", "HD2", "HE1", "HE2"], 
          "atom_types": ["N", "C", "C", "OA",  "C",  "A",  "A",   "A",   "A",   "A",   "A", "OA", "P",  "OA",  "OA",  "OA",   "HD", "H", "H", "H", "H", "H", "H", "H"],
  }, 
  "SEM": {"atom_names": ["N", "CA", "C", "O", "CB", "OG", "C'", "C1'", "C2'", "C3'", "C4'", "C5'", "C6'",  "H", "HA", "HB2", "HB3", "H'1", "H'2", "H2'", "H3'", "H4'", "H5'", "H6'"], 
          "atom_types": ["N", "C", "C", "OA",  "C", "OA", "C",   "A",   "A",   "A",   "A",   "A",   "A",   "HD", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],
  },
  "SEP": {"atom_names": ["N", "CA", "CB", "OG", "C", "O", "P", "O1P", "O2P", "O3P",   "H", "HA", "HB2", "HB3"], 
          "atom_types": ["N", "C",  "C",  "OA", "C", "OA", "P", "OA",  "OA",  "OA",   "HD", "H", "H", "H"],
  },
  "THP": {"atom_names": ["N", "CA", "C", "O", "CB2", "CG2", "SD", "CG1", "CB1",   "H", "HB23", "HB22", "HG22", "HG23", "HG13", "HG12", "HB12", "HB13"], 
          "atom_types": ["N", "C", "C", "OA",   "C",   "C",  "SA",   "C",   "C",   "HD", "H", "H", "H", "H", "H", "H", "H", "H"],
  },
  "TPO": {"atom_names": ["N", "CA", "CB", "CG2", "OG1", "P", "O1P", "O2P", "O3P", "C", "O",   "H", "HA", "HB", "HG21", "HG22", "HG23"], 
          "atom_types": ["N", "C",  "C",   "C",   "OA", "P", "OA",   "OA",  "OA", "C", "OA",   "HD", "H", "H", "H", "H", "H"],
  }, 
  "TY5": {"atom_names": ["N", "CA", "C", "O", "CB", "CG", "CD2", "CD1", "CE2", "CE1", "CZ", "OH", "C49", "C50", "C51", "C52", "C53", "C54", "C55",  "H", "HA", "H41", "H41A", "H43", "H47", "H44", "H46", "H49", "H49A", "H51", "H52", "H53", "H54", "H55"], 
          "atom_types": ["N", "C", "C", "OA", "C",   "A",   "A",   "A",   "A",   "A",  "A", "OA",   "C",   "A",   "A",   "A",   "A",   "A",   "A",  "HD", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],
  },
  "Z3E": {"atom_names": ["N", "CA", "C", "O", "CB", "OG1", "CG2", "C7", "C1", "C2", "C3", "C4", "C5", "C6",  "H", "HA", "HB", "HG2A", "HG2B", "HG2", "H7A", "H7", "H8", "H3", "H4", "H5", "H6"], 
          "atom_types": ["N", "C",  "C", "OA", "C",  "OA",   "C",  "C",  "A",  "A",  "A",  "A",  "A",  "A",  "HD", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],
  }
}
